version: 1.0.{build}
os:
  - Visual Studio 2019
clone_depth: 1
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
environment:
  matrix:
    - RUST: stable
    - RUST: beta
    - RUST: nightly

build_script: mk/appveyor.bat
