[package]
authors = ["Brian Smith <brian@briansmith.org>"]
build = "build.rs"
description = "A Rust interface for a simplification of BoringSSL's libcrypto."
license-file = "LICENSE"
name = "ring"
readme = "README.md"
repository = "https://github.com/briansmith/ring"
version = "0.1.0"

[lib]
name = "ring"

# XXX: When cross-compiling (e.g. i686 on x86_64), `cargo test` tries to run
# the doctests but that doesn't work. Disable the doctests for all platforms
# until we have a better workaround for this. See
# https://github.com/rust-lang/cargo/issues/1789
doctest=false

[dependencies]
lazy_static = "0.2.1"

[build-dependencies]
rustc-serialize = "0.3.15"

[dev-dependencies]
rustc-serialize = "0.3.15"

[build-dependencies.num]
version = "0.1.30"
default-features = false
features = ["bigint"]

[features]
# These features are documented in the top-level module's documentation.
disable_dev_urandom_fallback = []
no_heap = []
test_logging = []

# Fix the `bench`, `release`, and `test` profiles so they all have the
# same configuration.
#
# XXX: We can't build with `debug = true` yet because that breaks the
# Windows builds. See https://github.com/briansmith/ring/issues/44.

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
