[package]
name = "getrandom"
version = "0.2.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc-sgx-types = { git = "https://github.com/mobilecoinfoundation/mobilecoin.git", tag = "v6.0.2" }

[features]
js = []
