name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
jobs:
  rustfmt:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04

    steps:
      - uses: briansmith/actions-rs-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false
      - run: cargo fmt --all -- --check

  clippy:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04

    steps:
      - uses: briansmith/actions-rs-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false

      - run: mk/clippy.sh

  audit:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04

    steps:
      - uses: briansmith/actions-rs-toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: briansmith/actions-cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-audit
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-v2-cargo-audit-0.14.1

      - run: cargo install cargo-audit --locked --vers "0.14.1"

      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false

      - run: cargo generate-lockfile

      - run: cargo audit --deny warnings

  deny:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04

    steps:
      - uses: briansmith/actions-rs-toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: briansmith/actions-cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-deny
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-v2-cargo-deny-locked-0.9.1

      - run: cargo install cargo-deny --locked --vers "0.9.1"

      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false

      - run: cargo deny check

  # Verify that documentation builds.
  rustdoc:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        rust_channel:
          - stable
          - beta
          - nightly

        include:
          - target: x86_64-unknown-linux-gnu

    steps:
      - uses: briansmith/actions-rs-toolchain@v1
        with:
          override: true
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.rust_channel }}

      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false

      - run: |
          cargo doc --all-features

  package:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: windows-latest

    steps:
      - uses: briansmith/actions-checkout@v2
        with:
          persist-credentials: false

      - run: ./mk/install-build-tools.ps1

      - uses: briansmith/actions-rs-toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: sh mk/package.sh
        shell: bash
